### ISSUE TITLE
Not encoding UTF-8 correctly

### ISSUE THREAD

**Issue by shtse8** [FluentDOM/FluentDOM#66]
I am a Chinese developer and making Chinese website.

Code to reproduce:
```
$html = <<<EOF
<!DOCTYPE html>
<html prefix="og: http://ogp.me/ns#"><head><meta charset="UTF-8">
<title>网友终于肉搜出「范冰冰」家族照片，没想到看见她奶奶才发现「范冰冰是全家最难看的」！</title>
<body>
网友终于肉搜出「范冰冰」家族照片，没想到看见她奶奶才发现「范冰冰是全家最难看的」！
</body>
</html>
EOF;
$dom = FluentDOM::QueryCss($html, 'text/html');
echo $dom;
```

Result:
```
<!DOCTYPE html>
<html prefix="og: http://ogp.me/ns#"><head><meta charset="UTF-8"><title>&#32593;&#21451;&#32456;&#20110;&#32905;&#25628;&#20986;&#12300;&#33539;&#20912;&#20912;&#12301;&#23478;&#26063;&#29031;&#29255;&#65292;&#27809;&#24819;&#21040;&#30475;&#35265;&#22905;&#22902;&#22902;&#25165;&#21457;&#29616;&#12300;&#33539;&#20912;&#20912;&#26159;&#20840;&#23478;&#26368;&#38590;&#30475;&#30340;&#12301;&#65281;</title></head><body>
&#32593;&#21451;&#32456;&#20110;&#32905;&#25628;&#20986;&#12300;&#33539;&#20912;&#20912;&#12301;&#23478;&#26063;&#29031;&#29255;&#65292;&#27809;&#24819;&#21040;&#30475;&#35265;&#22905;&#22902;&#22902;&#25165;&#21457;&#29616;&#12300;&#33539;&#20912;&#20912;&#26159;&#20840;&#23478;&#26368;&#38590;&#30475;&#30340;&#12301;&#65281;
</body></html>
```

Expected Result:
```
<!DOCTYPE html>
<html prefix="og: http://ogp.me/ns#"><head><meta charset="UTF-8">
<title>网友终于肉搜出「范冰冰」家族照片，没想到看见她奶奶才发现「范冰冰是全家最难看的」！</title>
<body>
网友终于肉搜出「范冰冰」家族照片，没想到看见她奶奶才发现「范冰冰是全家最难看的」！
</body></html>
```

It is a known bug of PHP DomDocument. Here is the reference:
http://stackoverflow.com/questions/8218230/php-domdocument-loadhtml-not-encoding-utf-8-correctly

We should get the UTF-8 result instead of getting HTML-ENTITIES result. It doesn't make sense to get the final html with full of encoded utf-8 and making the size much larger.

**Comment by ThomasWeinert** [comment]
Right, I will check and try to fix this.

**Comment by shtse8** [comment]
Not only encoded utf-8 is returned.

Reproduce:
```
$html = '<div><p>Paragraph 1</p> <p>Paragraph 2</p><p>网友终于肉搜出「范冰冰」家族照片，没想到看见她奶奶才发现「范冰冰是全家最难看的」！</p></div>';
$doc = FluentDOM($html, 'html-fragment');
// $elements = $doc->find('p')->eq(1);
// foreach($elements as $element) {
	// $newElement = FluentDOM("<b>hi</b>", 'html-fragment');
	// $newElement->attr('title', 'test');
	// $element->replace($newElement);
// }
echo $doc->html();
```

Expected:
```
<p>Paragraph 1</p> <p>Paragraph 2</p><p>网友终于肉搜出「范冰冰」家族照片，没想到看见她奶奶才发现「范冰冰是全家最难看的」！</p>
```

Actual:
```
<p>Paragraph 1</p> <p>Paragraph 2</p>
<p>ç½�å��ç»�äº�è��æ��å�ºã��è��å�°å�°ã��å®¶æ��ç�§ç��ï¼�æ²¡æ�³å�°ç��è§�å¥¹å¥¶å¥¶æ��å��ç�°ã��è��å�°å�°æ�¯å�¨å®¶æ��é�¾ç��ç��ã��ï¼�</p>
```

**Comment by shtse8** [comment]
But it is fine using `html('some strings')`:

Code:
```
$doc = FluentDOM('<div></div>', 'html-fragment');
$doc->text('网友终于肉搜出「范冰冰」家族照片，没想到看见她奶奶才发现「范冰冰是全家最难看的」！');
echo $doc->text();
```

Result:
```
网友终于肉搜出「范冰冰」家族照片，没想到看见她奶奶才发现「范冰冰是全家最难看的」！
```

**Comment by ThomasWeinert** [comment]
Give me one or two weekends please :-)

I will try to add the issues as unit tests to make them reproducible.

**Comment by ThomasWeinert** [comment]
I just pushed https://github.com/FluentDOM/FluentDOM/commit/370e98f642506646e9c6eeaa20477fc9803ea309 

This is not the final fix, but it should improve the behavior.

**Comment by shtse8** [comment]
I want to try your new push, but I cannot use the `fluentdom` and `selectors-phpcss` in the same project.
It seems `selectors-phpcss` specify a version to make my composer not to install the new push of `fluentdom`. Do you have any idea to update to the latest push using composer?

```
"require": {
		"fluentdom/fluentdom": "dev-master#e2a47d5",
		"fluentdom/selectors-phpcss": "^1.0"
    }
```

when composer update:
```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove fluentdom/fluentdom dev-master
    - fluentdom/selectors-phpcss 1.0.0 requires fluentdom/fluentdom ^5.3 -> satisfiable by fluentdom/fluentdom[5.3.x-dev].
    - fluentdom/selectors-phpcss 1.0.1 requires fluentdom/fluentdom ^5.3||^6.0 -> satisfiable by fluentdom/fluentdom[5.3.x-dev, 6.0.x-dev, 6.1.x-dev].
    - Can only install one of: fluentdom/fluentdom[dev-master, 5.3.x-dev].
    - Can only install one of: fluentdom/fluentdom[dev-master, 6.0.x-dev].
    - Can only install one of: fluentdom/fluentdom[dev-master, 6.1.x-dev].
    - Installation request for fluentdom/fluentdom dev-master#e2a47d5 -> satisfiable by fluentdom/fluentdom[dev-master].
    - Installation request for fluentdom/selectors-phpcss ^1.0 -> satisfiable by fluentdom/selectors-phpcss[1.0.0, 1.0.1].
```

**Comment by shtse8** [comment]
Anyway, I have downloaded the lastest clone and replaced the whole folder manually. I can test now.
It seems the behavior is the same using `FluentDOM::QueryCss`, but it is fine using `new HTML()`.

**Comment by shtse8** [comment]
Hi, Any updates?

**Comment by ThomasWeinert** [comment]
I added some RegEx to the HTML loader to fetch the encoding from the meta tags - default is UTF-8 now. Additionally I did a lot of rework on the load/save process from HTML - testing it with Chinese characters. The changes are pushed to the 6.1 branch and I added the version to the CSS Selector package, so a composer install allowing the dev versions should work now.

If you could test it out and send me (small) examples that do not work as expected, I would appreciate it.

**Comment by shtse8** [comment]
@ThomasWeinert Hi, could you give me a sample of composer.json to include the dev version? I have tried the following but without any luck.

```
{
	"repositories": [
      {
        "type": "vcs",
        "url": "https://github.com/FluentDOM/FluentDOM"
      }
    ],
	"require": {
		"fluentdom/fluentdom": "dev-master#6.1",
		"fluentdom/selectors-phpcss": "^1.0"
    }
}
```

Result:
```
Loading composer repositories with package information                                                                                                                                 Updating dependencies (including require-dev)         Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install fluentdom/fluentdom dev-master
    - fluentdom/selectors-phpcss 1.0.1 requires fluentdom/fluentdom ^5.3||^6.0 -> satisfiable by fluentdom/fluentdom[5.3.x-dev, 6.0.x-dev, 6.1.x-dev].
    - fluentdom/selectors-phpcss 1.0.0 requires fluentdom/fluentdom ^5.3 -> satisfiable by fluentdom/fluentdom[5.3.x-dev].
    - fluentdom/selectors-phpcss 1.0.1 requires fluentdom/fluentdom ^5.3||^6.0 -> satisfiable by fluentdom/fluentdom[5.3.x-dev, 6.0.x-dev, 6.1.x-dev].
    - Can only install one of: fluentdom/fluentdom[dev-master, 5.3.x-dev].
    - Can only install one of: fluentdom/fluentdom[dev-master, 6.0.x-dev].
    - Can only install one of: fluentdom/fluentdom[dev-master, 6.1.x-dev].
    - Can only install one of: fluentdom/fluentdom[dev-master, 5.3.x-dev].
    - Can only install one of: fluentdom/fluentdom[dev-master, 6.0.x-dev].
    - Can only install one of: fluentdom/fluentdom[dev-master, 6.1.x-dev].
    - Installation request for fluentdom/fluentdom dev-master#6.1 -> satisfiable by fluentdom/fluentdom[dev-master].
    - Installation request for fluentdom/selectors-phpcss ^1.0 -> satisfiable by fluentdom/selectors-phpcss[1.0.0, 1.0.1].


```

and, I also tried.

```
{
	"require": {
		"fluentdom/fluentdom": "^6.1",
		"fluentdom/selectors-phpcss": "^1.0"
    }
}
```

Result:
```
Loading composer repositories with package information                                                                                                                                 Updating dependencies (including require-dev)         Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package fluentdom/fluentdom could not be found in any version, there may be a typo in the package name.
  Problem 2
    - fluentdom/selectors-phpcss 1.0.1 requires fluentdom/fluentdom ^5.3||^6.0 -> no matching package found.
    - fluentdom/selectors-phpcss 1.0.0 requires fluentdom/fluentdom ^5.3 -> no matching package found.
    - fluentdom/selectors-phpcss 1.0.1 requires fluentdom/fluentdom ^5.3||^6.0 -> no matching package found.
    - Installation request for fluentdom/selectors-phpcss ^1.0 -> satisfiable by fluentdom/selectors-phpcss[1.0.0, 1.0.1].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

```

**Comment by shtse8** [comment]
Okay, I can use it now with the following composer.

```
{
	"repositories": [
      {
        "type": "vcs",
        "url": "https://github.com/FluentDOM/FluentDOM"
      }
    ],
	"require": {
		"fluentdom/fluentdom": "dev-master as 6.1",
		"fluentdom/selectors-phpcss": "^1.0.1"
    }
}


```

**Comment by shtse8** [comment]
```
$doc = FluentDOM('<div></div>', 'html-fragment');
$doc->html(FluentDOM('网友终于肉搜出「范冰冰」家族照片，没想到看见她奶奶才发现「范冰冰是全家最难看的」！', 'html-fragment'));
echo $doc;
```

Expected:
```
<div>网友终于肉搜出「范冰冰」家族照片，没想到看见她奶奶才发现「范冰冰是全家最难看的」！</div>
```


Actual:
```
<div>Ã§Â½Â�Ã¥Â�Â�Ã§Â»Â�Ã¤ÂºÂ�Ã¨Â�Â�Ã¦Â�Â�Ã¥Â�ÂºÃ£Â�Â�Ã¨Â�Â�Ã¥Â�Â°Ã¥Â�Â°Ã£Â�Â�Ã¥Â®Â¶Ã¦Â�Â�Ã§Â�Â§Ã§Â�Â�Ã¯Â¼Â�Ã¦Â²Â¡Ã¦Â�Â³Ã¥Â�Â°Ã§Â�Â�Ã¨Â§Â�Ã¥Â¥Â¹Ã¥Â¥Â¶Ã¥Â¥Â¶Ã¦Â�Â�Ã¥Â�Â�Ã§Â�Â°Ã£Â�Â�Ã¨Â�Â�Ã¥Â�Â°Ã¥Â�Â°Ã¦Â�Â¯Ã¥Â�Â¨Ã¥Â®Â¶Ã¦Â�Â�Ã©Â�Â¾Ã§Â�Â�Ã§Â�Â�Ã£Â�Â�Ã¯Â¼Â�
</div>
```

**Comment by shtse8** [comment]
Code:
```
$html = '<div><p>Paragraph 1</p> <p>Paragraph 2</p><p>网友终于肉搜出「范冰冰」家族照片，没想到看见她奶奶才发现「范冰冰是全家最难看的」！</p></div>';
$doc = FluentDOM($html, 'html-fragment');
echo $doc->html();
```

Expected:
```
<div><p>Paragraph 1</p> <p>Paragraph 2</p><p>网友终于肉搜出「范冰冰」家族照片，没想到看见她奶奶才发现「范冰冰是全家最难看的」！</p></div>
```

Actaul:
```
<p>Paragraph 1</p> <p>Paragraph 2</p>
<p>ç½�å��ç»�äº�è��æ��å�ºã��è��å�°å�°ã��å®¶æ��ç�§ç��ï¼�æ²¡æ�³å�°ç��è§�å¥¹å¥¶å¥¶æ��å��ç�°ã��è��å�°å�°æ�¯å�¨å®¶æ��é�¾ç��ç��ã��ï¼�</p>
```

**Comment by shtse8** [comment]
any news on this?

**Comment by ThomasWeinert** [comment]
I just pushed a fix for html-fragments: https://github.com/FluentDOM/FluentDOM/commit/9b0daec83958dc6c772d2b88da91f6e6da328a41

**Comment by shtse8** [comment]
@ThomasWeinert Thanks for your updates.
But  the `html-fragment` out is still wrong.

### Code to reproduce
```
$doc = FluentDOM('<div></div>', 'html-fragment');
$doc->html(FluentDOM('网友终于肉搜出「范冰冰」家族照片，没想到看见她奶奶才发现「范冰冰是全家最难看的」！', 'html-fragment'));
echo $doc;
```

### ExpectedResult:
```
<div>网友终于肉搜出「范冰冰」家族照片，没想到看见她奶奶才发现「范冰冰是全家最难看的」！</div>
```

### Actual Result:
```
<div>Ã§Â½Â�Ã¥Â�Â�Ã§Â»Â�Ã¤ÂºÂ�Ã¨Â�Â�Ã¦Â�Â�Ã¥Â�ÂºÃ£Â�Â�Ã¨Â�Â�Ã¥Â�Â°Ã¥Â�Â°Ã£Â�Â�Ã¥Â®Â¶Ã¦Â�Â�Ã§Â�Â§Ã§Â�Â�Ã¯Â¼Â�Ã¦Â²Â¡Ã¦Â�Â³Ã¥Â�Â°Ã§Â�Â�Ã¨Â§Â�Ã¥Â¥Â¹Ã¥Â¥Â¶Ã¥Â¥Â¶Ã¦Â�Â�Ã¥Â�Â�Ã§Â�Â°Ã£Â�Â�Ã¨Â�Â�Ã¥Â�Â°Ã¥Â�Â°Ã¦Â�Â¯Ã¥Â�Â¨Ã¥Â®Â¶Ã¦Â�Â�Ã©Â�Â¾Ã§Â�Â�Ã§Â�Â�Ã£Â�Â�Ã¯Â¼Â�
</div>
```

**Comment by ThomasWeinert** [comment]
That uses a different method of the HTML loader (`load()` vs `loadFragment()`). Added test, fixed and pushed: https://github.com/FluentDOM/FluentDOM/commit/28c53f17432611a3fa9f8c823d749bd425e160b9

**Comment by shtse8** [comment]
Works Great!
But why is the closing div in the next line?

### Code to reproduce
```php
$doc = FluentDOM('<div></div>', 'html-fragment');
$doc->html(FluentDOM('hihi', 'html-fragment'));
echo $doc;
```

### Expected Result:
```
<div>hihi</div>
```

### Actual Result:
```
<div>hihi
</div>
```

**Comment by ThomasWeinert** [comment]
I will move the formatting problem to a new issue
